### PR TITLE
Camel 16012 remove prefix 01

### PR DESCRIPTION
**Pull request by metters**
In this PR I fixed some minor issues in the READMEs, as well as some sonar issues in the classes.
Then I migrated the modules starting with the characters 'a' and 'b'

### CODE REVIEW

**Comment by metters** [comment]
There seems to be a problem with the build. I am going to figure out whats wrong later - it's too late now.

**Comment by metters** [comment]
Found it - the renaming of intellij was not intelligent enough to also rename the reference in the root pom, so I had to fix that manually

**Comment by metters** [comment]
Now the build fails like it does locally. I have mentioned this already before I started working on the ticket [in JIRA](https://issues.apache.org/jira/browse/CAMEL-16012?focusedCommentId=17280040&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17280040)

There is a problem with the example projects main-xml and ssh.

**Comment by davsclaus** [comment]
I have fixed the xml example and the ssh has been removed

**Comment by metters** [comment]
Thank you very much

**Comment by davsclaus** [comment]
@metters let me know when you think this PR is ready to review/merge.

**Comment by metters** [comment]
@davsclaus i will. I just enjoyed a few lazy days during Chinese New Year.
I think I will find some time this weekend

**Comment by metters** [comment]
@davsclaus , the PR is ready for review and merge

**Review by oscerd — APPROVED** [review]

**Review by davsclaus — APPROVED** [review]

**Pull request merged**
