### PR TITLE
Fix subfolders reference

### PR DESCRIPTION
**Pull request by mateusalxd**
The link of some examples were invalid.

### CODE REVIEW

**Review by oscerd — CHANGES_REQUESTED** [review]
Thanks but this is autogenerated from a maven plugin in camel core. This will be overridden.

**Comment by mateusalxd** [comment]
> Thanks but this is autogenerated from a maven plugin in camel core. This will be overridden.

Do you think it makes sense to fix this? If yes, could you give a brief context of where to change it? With that I can analyze if it's something I can do.

**Comment by oscerd** [comment]
The Mojo it's here: https://github.com/apache/camel/blob/main/tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java

**Comment by mateusalxd** [comment]
Thanks, I'll study a bit and I'll open a PR if I find a solution.

**Pull request closed without merging**
