### PR TITLE
CAMEL-20253: camel-jbang - Add support for jolokia 2.x

### PR DESCRIPTION
**Pull request by kulagaIA**
enabled jolokia in platform-http-main

### CODE REVIEW

**Review by oscerd — APPROVED** [review]

**Comment by kulagaIA** [comment]
wait this needs pr in camel repo to be merged first

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
@kulagaIA we have merged jolokia into main so I think this PR is ready

**Comment by kulagaIA** [comment]
made it mergeable, but mind that this example needs
<dependency>
    <groupId>org.apache.camel</groupId>
    <artifactId>camel-jolokia</artifactId>
</dependency>
so if separate jolokia module is absent this example will not compile

**Comment by davsclaus** [comment]
Ah yeah we have jolokia directly now, so `camel-jolokia` should be removed. 

Then later when we have jolokia as pluggable to main-http we can add a dependency back.

You may also want to update the readme file and mention a bit about jolokia and show how to use it a little bit so users can better understand

**Pull request merged**
