### PR TITLE
A Camel standalone example using Spring Boot CLI

### PR DESCRIPTION
**Pull request by vinodpahuja**

### CODE REVIEW

**Comment by davsclaus** [comment]
Spring Boot examples should be in 
https://github.com/apache/camel-spring-boot-examples

This repository is for standalone examples that do not use spring boot

**Comment by vinodpahuja** [comment]
> Spring Boot examples should be in https://github.com/apache/camel-spring-boot-examples
> 
> This repository is for standalone examples that do not use spring boot

Initially I thought the same, but this example is based on standalone camel execution using spring boot cli and not using [camel-spring-boot](https://github.com/apache-camel/camel-spring-boot) support.
For the camel-spring-boot I am planning to add another example based on [camel extension] (https://github.com/apache-camel/camel-spring-boot-cli) for spring-boot-cli

**Comment by davsclaus** [comment]
Okay but I think this is too confusing for users that there is any kind of spring boot here. Your example belongs in that other repo I pointed to

And btw Camel has its own CLI with camel-jbang
https://camel.apache.org/manual/camel-jbang.html

**Comment by vinodpahuja** [comment]
> Okay but I think this is too confusing for users that there is any kind of spring boot here. Your example belongs in that other repo I pointed to
 
Yes at first it seems, but camel was designed to work [first class with spring](https://camel.apache.org/manual/spring.html)

> And btw Camel has its own CLI with camel-jbang https://camel.apache.org/manual/camel-jbang.html

Yes I understand, but it looks jbang is an additional stack to support camel for Spring Boot users (lovers)

Also for moving to the other examples repo it may needs to support camel-spring-boot-starters.

**Comment by davsclaus** [comment]
The example does not belong here

**Comment by vinodpahuja** [comment]
Thanks for suggestion. I have moved it to https://github.com/apache/camel-spring-boot-examples/pull/79

**Pull request closed without merging**
