### PR TITLE
CAMEL-17762: updated the resume examples

### PR DESCRIPTION
**Pull request by orpiske**
This updates the resume-api examples according to the recent cleanups on
the resume API.

### CODE REVIEW

**Comment by orpiske** [comment]
This one will fail until apache/camel#7540 is merged, so we'd better wait.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Looks really good - easier to use and understand for end users

**Comment by orpiske** [comment]
> Looks really good - easier to use and understand for end users

Thanks! Some of these ideas came up after a brainstorming session w/ @lburgazzoli as we were talking about what would it take to bring this to Camel K. 

And I hope it will be even easier in the future. I also plan to implement some kind of auto-discovery for adapters, caches and strategies. I don't really know how I will do that yet, though. So I guess this is for 3.18.

**Comment by davsclaus** [comment]
Yeah one battle at a time

**Pull request merged**
