### PR TITLE
CAMEL-17575: Update `Main` examples entry to use package scanning

### PR DESCRIPTION
**Pull request by tmarwen**
### Change scope
- Updated all (straightforward `MyApplication` + `MyRouteBuilder`) examples to use base package scanning
- Updated examples `application.properties` to link documentation
- Externalized configuration for `artemis` and `widget-gadget-java` examples
- Split producer and consumer routes for `debezium-eventhubs-blob` example
- Split `search` and `savedsearch` routes for `splunk` example
- Added annotation-based configuration for `netty-custom-correlation` 

### Implementation notes
- Some test fixtures have been updated to use package scanning as well such as `org.apache.camel.example.artemis.ArtemisTest` avoiding manual binding and route declaration while keeping the same implementation style as the main example class
- Below modules tests where failing before and after implementation changes:
  - camel-example-aggregate-dist
  - camel-example-any23
  - camel-example-artemis
  - camel-example-endpointdsl-aws2-s3-kafka
  - camel-example-debezium
  - camel-example-jooq
  - camel-example-kamelet-main
  - camel-example-oaipmh
  - camel-example-transformer-demo

Refs [CAMEL-17575](https://issues.apache.org/jira/browse/CAMEL-17575)

### CODE REVIEW

**Review by essobedo — APPROVED** [review]
Nice work 👍 Have checked locally that the tests of the examples that you modified still pass and those examples are still working?

**Review by oscerd — CHANGES_REQUESTED** [review]
All looks good, but please add Licenses.

**Review by davsclaus — APPROVED** [review]

**Comment by davsclaus** [comment]
Thanks a lot for the help, as Andrea mentions then some files lacks the license headers in the top.

**Comment by tmarwen** [comment]
@essobedo all the modules changed have been tested unless the ones I mentioned in my PR description which have been failing prior to applying my changes (I have run various dry test runs to check before applying changes to make sure those tests are not failing randomly).
I am happy to help fixing these if those shows to be failing consistently and not only on my own box.

**Comment by essobedo** [comment]
I confirm that `camel-example-transformer-demo`, `kamelet-main` and `artemis` fail systematically, maybe there are regressions behind? I case of `oaipmh`, it is due to the slowness of the remote webservice, I guess we could increase the timeout. 
For the rest, I could not reproduce. What kind of failure did you get? random or not?

**Comment by tmarwen** [comment]
@essobedo excluding the modules you mentioned being failing systematically for you, below are the list of ones remaining failing for me:
* `camel-example-aggregate-dist`: this module test fixture succeeds sometimes when exceeding the timeout within the test assertion
* `camel-example-endpointdsl-aws2-s3-kafka`: this module succeeds when forcing a `Thread.sleep(1000)` before sending the first message triggering the routes `template.send("direct:putObject", exchange -> { //...});`. Otherwise it succeeds when run separately (not as part of all the project test run).
* `camel-example-debezium`: this module test fixture succeeds as well only when ran separately
* `camel-example-jooq`:  this module test fixture succeeds as well only when ran separately

**Comment by davsclaus** [comment]
I created a ticket about those problematic examples
https://issues.apache.org/jira/browse/CAMEL-17847

**Pull request merged**
